[build]
builder = "NIXPACKS"
buildCommand = "curl -LsSf https://astral.sh/uv/install.sh | sh && source $HOME/.local/bin/env && cd voice-quiz-back && uv venv && uv pip install -r requirements.txt"
watchPatterns = ["voice-quiz-back/**"]

[deploy]
startCommand = "cd voice-quiz-back && source .venv/bin/activate && python run.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
