[build]
builder = "NIXPACKS"
buildCommand = "curl -LsSf https://astral.sh/uv/install.sh | sh && export PATH=\"$HOME/.cargo/bin:$PATH\" && cd voice-quiz-back && uv pip install --system -r requirements.txt"
watchPatterns = ["voice-quiz-back/**"]

[deploy]
startCommand = "cd voice-quiz-back && python run.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
