[build]
builder = "NIXPACKS"
buildCommand = "cd voice-quiz-back && pip install -r requirements.txt"
watchPatterns = ["voice-quiz-back/**"]

[deploy]
startCommand = "cd voice-quiz-back && python run.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
